package values

const GAME_OVER_EVENT string = "GAME_OVER_EVENT"
const GAME_RESTART_EVENT string = "GAME_RESTART_EVENT"
const PLAYER_ATTACK_EVENT string = "PLAYER_ATTACK_EVENT"
const ENEMY_ATTACK_EVENT string = "ENEMY_ATTACK_EVENT"
const ENEMY_DEAD_EVENT string = "ENEMY_DEAD_EVENT"
